{% set name = "xwidgets" %}
{% set version = "0.27.3" %}
{% set sha256 = "5c5d000582efcf0c782c09663936ba6a2bebca94a5a6e42da187f7b00d649c8f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/jupyter-xeus/xwidgets/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win and vc<14]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - cmake
    - {{ compiler('cxx') }}
    - make  # [unix]
  host:
    - xeus >=3.0,<4.0
    - xproperty >=0.11.0,<0.12
    # Version contraints of xtl, nlohmann_json, and cppzmq are set as run_contraints of xeus
    - cppzmq
    - xtl
    - nlohmann_json >=3.9.1,<3.10
  run:
    # cppzmq, xtl, xproperty and nlohmann_json
    # are header-only but required at runtime (!)
    # in the context of xwidgets being used in xeus-cling
    - {{ pin_compatible('cppzmq', max_pin='x.x') }}
    - {{ pin_compatible('xtl', max_pin='x.x') }}
    - {{ pin_compatible('xproperty', max_pin='x.x') }}
    - {{ pin_compatible('nlohmann_json', max_pin='x.x') }}

test:
  commands:
    - test -d ${PREFIX}/include/xwidgets  # [unix]
    - test -f ${PREFIX}/include/xwidgets/xtransport.hpp  # [unix]
    - test -f ${PREFIX}/lib/cmake/xwidgets/xwidgetsConfig.cmake  # [unix]
    - test -f ${PREFIX}/lib/cmake/xwidgets/xwidgetsConfigVersion.cmake  # [unix]
    - if exist %LIBRARY_PREFIX%\include\xwidgets\xtransport.hpp (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\xwidgetsConfig.cmake (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\xwidgetsConfigVersion.cmake (exit 0) else (exit 1)  # [win]

about:
  home: http://quantstack.net/xwidgets
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: C++ implementation of the Jupyter Interactive widgets
  doc_url: http://xwidgets.readthedocs.io
  dev_url: https://github.com/jupyter-xeus/xwidgets

extra:
  recipe-maintainers:
    - SylvainCorlay
    - JohanMabille
    - gouarin
    - martinRenou
