{% set name = "xwidgets" %}
{% set version = "0.29.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/jupyter-xeus/xwidgets/archive/{{ version }}.tar.gz
  sha256: 07c789b7936b19a123f37ac1edfd0598a89f23e02d4eeffc9976817be68bee42

build:
  number: 0
  skip: true  # [win and vc<14]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - cmake
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - make  # [unix]
  host:
    - xeus >=5,<6
    - xproperty >=0.12.0,<0.13
    # Version contraints, nlohmann_json, and cppzmq are set as run_contraints of xeus
    - cppzmq
    - nlohmann_json >=3.11
  run:
    # cppzmq, xproperty and nlohmann_json
    # are header-only but required at runtime (!)
    # in the context of xwidgets being used in xeus-cling
    - {{ pin_compatible('cppzmq', max_pin='x.x') }}
    - {{ pin_compatible('xproperty', max_pin='x.x') }}
    - {{ pin_compatible('nlohmann_json', max_pin='x.x.x') }}

test:
  commands:
    - test -d ${PREFIX}/include/xwidgets  # [unix]
    - test -f ${PREFIX}/include/xwidgets/xtransport.hpp  # [unix]
    - test -f ${PREFIX}/lib/cmake/xwidgets/xwidgetsConfig.cmake  # [unix]
    - test -f ${PREFIX}/lib/cmake/xwidgets/xwidgetsConfigVersion.cmake  # [unix]
    - if exist %LIBRARY_PREFIX%\include\xwidgets\xtransport.hpp (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\xwidgetsConfig.cmake (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\xwidgetsConfigVersion.cmake (exit 0) else (exit 1)  # [win]

about:
  home: http://quantstack.net/xwidgets
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: C++ implementation of the Jupyter Interactive widgets
  doc_url: http://xwidgets.readthedocs.io
  dev_url: https://github.com/jupyter-xeus/xwidgets

extra:
  recipe-maintainers:
    - SylvainCorlay
    - JohanMabille
    - gouarin
    - martinRenou
