appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: LU+BXV2/NopDaObmBKuBFBO9AcG4P+MZa3tFpyYP+2hRcZe9ims7xeUEyvJ8U7DGahXLl1DhyH2GgVl9YONG1DRFvH8d1oeIFwtKMjRLUpqMkK51VZZTwFrJhC7tNaW6VXEQwE7KQQk3cgVvniB2L9ia+XPi5GYNb1ncwB9bpIPtWKlvzjTNRe6X655y3LbP1qVX3knY96NI/0PpDYqfQTLXbMBX4909z8Y6zu1jl/QUy0uV/+RtAE64ZLz4r1HkKVbPUX7oIBPO8nFGxffZBCpoaUQklo1/0gWsN7LEEv2LpnddemQMqDTFiL6NJOTi8ukqaazdx1q4QTKOdKcvrEuAvtP6wEnQg/U7ldf51+QbXN2m1GBTr89n6ajBobGCyLS1N9JFo8+GWi3Qj5AxtZF4oszXWy24JIKtP5nvo/rfZ7X3sWodR3lsF5lJ5dlgEouyYAl1fhf1zJOqCKGcVRaFWDD4gygP/kw+utuRCLRpA2MEK/7umE9cP3dyInewMyi+EMx/HJSMcgnytPYwVpfPxAC5rhUdl3Q6sKsgVuv73qWDv+AfPN+YeuwXct6xIuA7bdh3Gnv58zHoLyajsNxeLR9U8YOGdATWYoSAEP6wMJ3XuvVhpqAAaj+8ZE/AI0DoSRryQBfiUZVZX5s050S6wgOlNucj/BefXwEfCK8=}
provider:
  win: azure
